#############################################################################
# Makefile for building: SmartMentor
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  SmartMentor.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile SmartMentor.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SmartMentor1.0.0
DISTDIR = /home/jha58/CS3307B/group65-submission/.tmp/SmartMentor1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
	QuestionGeneration.cpp \
	User.cpp \
	Quiz.cpp \
	Question.cpp \
	Screens/BlitzQuizScreen.cpp \
	Screens/BlitzQuizSetupScreen.cpp \
	Screens/CustomQuizSetupScreen.cpp \
	Screens/MainMenu.cpp \
	Screens/ModeSelectScreen.cpp \
	Screens/QuizScreen.cpp \
	Screens/QuizSetupScreen.cpp \
	Screens/StatsMenu.cpp \
	translations/mymemorytranslator.cpp \
	moc_BlitzQuizScreen.cpp \
	moc_BlitzQuizSetupScreen.cpp \
	moc_CustomQuizSetupScreen.cpp \
	moc_MainMenu.cpp \
	moc_ModeSelectScreen.cpp \
	moc_QuizScreen.cpp \
	moc_QuizSetupScreen.cpp \
	moc_StatsMenu.cpp \
	moc_mymemorytranslator.cpp

OBJECTS       = main.o \
	QuestionGeneration.o \
	User.o \
	Quiz.o \
	Question.o \
	BlitzQuizScreen.o \
	BlitzQuizSetupScreen.o \
	CustomQuizSetupScreen.o \
	MainMenu.o \
	ModeSelectScreen.o \
	QuizScreen.o \
	QuizSetupScreen.o \
	StatsMenu.o \
	mymemorytranslator.o \
	moc_BlitzQuizScreen.o \
	moc_BlitzQuizSetupScreen.o \
	moc_CustomQuizSetupScreen.o \
	moc_MainMenu.o \
	moc_ModeSelectScreen.o \
	moc_QuizScreen.o \
	moc_QuizSetupScreen.o \
	moc_StatsMenu.o \
	moc_mymemorytranslator.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SmartMentor.pro QuestionGeneration.h \
		ollama.hpp \
		User.h \
		Quiz.h \
		Question.h \
		Screens/BlitzQuizScreen.cpp \
		Screens/BlitzQuizScreen.cpp:Zone.Identifier \
		Screens/BlitzQuizScreen.h \
		Screens/BlitzQuizScreen.h:Zone.Identifier \
		Screens/BlitzQuizSetupScreen.cpp \
		Screens/BlitzQuizSetupScreen.cpp:Zone.Identifier \
		Screens/BlitzQuizSetupScreen.h \
		Screens/BlitzQuizSetupScreen.h:Zone.Identifier \
		Screens/CustomQuizSetupScreen.cpp \
		Screens/CustomQuizSetupScreen.cpp:Zone.Identifier \
		Screens/CustomQuizSetupScreen.h \
		Screens/CustomQuizSetupScreen.h:Zone.Identifier \
		Screens/MainMenu.cpp \
		Screens/MainMenu.cpp:Zone.Identifier \
		Screens/MainMenu.h \
		Screens/MainMenu.h:Zone.Identifier \
		Screens/ModeSelectScreen.cpp \
		Screens/ModeSelectScreen.cpp:Zone.Identifier \
		Screens/ModeSelectScreen.h \
		Screens/ModeSelectScreen.h:Zone.Identifier \
		Screens/QuizScreen.cpp \
		Screens/QuizScreen.cpp:Zone.Identifier \
		Screens/QuizScreen.h \
		Screens/QuizScreen.h:Zone.Identifier \
		Screens/QuizSetupScreen.cpp \
		Screens/QuizSetupScreen.cpp:Zone.Identifier \
		Screens/QuizSetupScreen.h \
		Screens/QuizSetupScreen.h:Zone.Identifier \
		Screens/StatsMenu.cpp \
		Screens/StatsMenu.cpp:Zone.Identifier \
		Screens/StatsMenu.h \
		Screens/StatsMenu.h:Zone.Identifier \
		translations/mymemorytranslator.cpp \
		translations/mymemorytranslator.cpp:Zone.Identifier \
		translations/mymemorytranslator.h \
		translations/mymemorytranslator.h:Zone.Identifier main.cpp \
		QuestionGeneration.cpp \
		User.cpp \
		Quiz.cpp \
		Question.cpp \
		Screens/BlitzQuizScreen.cpp \
		Screens/BlitzQuizScreen.cpp:Zone.Identifier \
		Screens/BlitzQuizScreen.h:Zone.Identifier \
		Screens/BlitzQuizSetupScreen.cpp \
		Screens/BlitzQuizSetupScreen.cpp:Zone.Identifier \
		Screens/BlitzQuizSetupScreen.h:Zone.Identifier \
		Screens/CustomQuizSetupScreen.cpp \
		Screens/CustomQuizSetupScreen.cpp:Zone.Identifier \
		Screens/CustomQuizSetupScreen.h:Zone.Identifier \
		Screens/MainMenu.cpp \
		Screens/MainMenu.cpp:Zone.Identifier \
		Screens/MainMenu.h:Zone.Identifier \
		Screens/ModeSelectScreen.cpp \
		Screens/ModeSelectScreen.cpp:Zone.Identifier \
		Screens/ModeSelectScreen.h:Zone.Identifier \
		Screens/QuizScreen.cpp \
		Screens/QuizScreen.cpp:Zone.Identifier \
		Screens/QuizScreen.h:Zone.Identifier \
		Screens/QuizSetupScreen.cpp \
		Screens/QuizSetupScreen.cpp:Zone.Identifier \
		Screens/QuizSetupScreen.h:Zone.Identifier \
		Screens/StatsMenu.cpp \
		Screens/StatsMenu.cpp:Zone.Identifier \
		Screens/StatsMenu.h:Zone.Identifier \
		translations/mymemorytranslator.cpp \
		translations/mymemorytranslator.cpp:Zone.Identifier \
		translations/mymemorytranslator.h:Zone.Identifier
QMAKE_TARGET  = SmartMentor
DESTDIR       = 
TARGET        = SmartMentor


first: all
####### Build rules

SmartMentor:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SmartMentor.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SmartMentor.pro
	$(QMAKE) -o Makefile SmartMentor.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
SmartMentor.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile SmartMentor.pro

qmake_all: FORCE


all: Makefile SmartMentor

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents QuestionGeneration.h ollama.hpp User.h Quiz.h Question.h Screens/BlitzQuizScreen.cpp Screens/BlitzQuizScreen.cpp:Zone.Identifier Screens/BlitzQuizScreen.h Screens/BlitzQuizScreen.h:Zone.Identifier Screens/BlitzQuizSetupScreen.cpp Screens/BlitzQuizSetupScreen.cpp:Zone.Identifier Screens/BlitzQuizSetupScreen.h Screens/BlitzQuizSetupScreen.h:Zone.Identifier Screens/CustomQuizSetupScreen.cpp Screens/CustomQuizSetupScreen.cpp:Zone.Identifier Screens/CustomQuizSetupScreen.h Screens/CustomQuizSetupScreen.h:Zone.Identifier Screens/MainMenu.cpp Screens/MainMenu.cpp:Zone.Identifier Screens/MainMenu.h Screens/MainMenu.h:Zone.Identifier Screens/ModeSelectScreen.cpp Screens/ModeSelectScreen.cpp:Zone.Identifier Screens/ModeSelectScreen.h Screens/ModeSelectScreen.h:Zone.Identifier Screens/QuizScreen.cpp Screens/QuizScreen.cpp:Zone.Identifier Screens/QuizScreen.h Screens/QuizScreen.h:Zone.Identifier Screens/QuizSetupScreen.cpp Screens/QuizSetupScreen.cpp:Zone.Identifier Screens/QuizSetupScreen.h Screens/QuizSetupScreen.h:Zone.Identifier Screens/StatsMenu.cpp Screens/StatsMenu.cpp:Zone.Identifier Screens/StatsMenu.h Screens/StatsMenu.h:Zone.Identifier translations/mymemorytranslator.cpp translations/mymemorytranslator.cpp:Zone.Identifier translations/mymemorytranslator.h translations/mymemorytranslator.h:Zone.Identifier $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp QuestionGeneration.cpp User.cpp Quiz.cpp Question.cpp Screens/BlitzQuizScreen.cpp Screens/BlitzQuizScreen.cpp:Zone.Identifier Screens/BlitzQuizScreen.h:Zone.Identifier Screens/BlitzQuizSetupScreen.cpp Screens/BlitzQuizSetupScreen.cpp:Zone.Identifier Screens/BlitzQuizSetupScreen.h:Zone.Identifier Screens/CustomQuizSetupScreen.cpp Screens/CustomQuizSetupScreen.cpp:Zone.Identifier Screens/CustomQuizSetupScreen.h:Zone.Identifier Screens/MainMenu.cpp Screens/MainMenu.cpp:Zone.Identifier Screens/MainMenu.h:Zone.Identifier Screens/ModeSelectScreen.cpp Screens/ModeSelectScreen.cpp:Zone.Identifier Screens/ModeSelectScreen.h:Zone.Identifier Screens/QuizScreen.cpp Screens/QuizScreen.cpp:Zone.Identifier Screens/QuizScreen.h:Zone.Identifier Screens/QuizSetupScreen.cpp Screens/QuizSetupScreen.cpp:Zone.Identifier Screens/QuizSetupScreen.h:Zone.Identifier Screens/StatsMenu.cpp Screens/StatsMenu.cpp:Zone.Identifier Screens/StatsMenu.h:Zone.Identifier translations/mymemorytranslator.cpp translations/mymemorytranslator.cpp:Zone.Identifier translations/mymemorytranslator.h:Zone.Identifier $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_BlitzQuizScreen.cpp moc_BlitzQuizSetupScreen.cpp moc_CustomQuizSetupScreen.cpp moc_MainMenu.cpp moc_ModeSelectScreen.cpp moc_QuizScreen.cpp moc_QuizSetupScreen.cpp moc_StatsMenu.cpp moc_mymemorytranslator.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_BlitzQuizScreen.cpp moc_BlitzQuizSetupScreen.cpp moc_CustomQuizSetupScreen.cpp moc_MainMenu.cpp moc_ModeSelectScreen.cpp moc_QuizScreen.cpp moc_QuizSetupScreen.cpp moc_StatsMenu.cpp moc_mymemorytranslator.cpp
moc_BlitzQuizScreen.cpp: Screens/BlitzQuizScreen.h \
		Screens/QuizScreen.h \
		User.h \
		Quiz.h \
		Question.h \
		translations/mymemorytranslator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jha58/CS3307B/group65-submission/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jha58/CS3307B/group65-submission -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Screens/BlitzQuizScreen.h -o moc_BlitzQuizScreen.cpp

moc_BlitzQuizSetupScreen.cpp: Screens/BlitzQuizSetupScreen.h \
		Screens/QuizSetupScreen.h \
		User.h \
		Quiz.h \
		Question.h \
		translations/mymemorytranslator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jha58/CS3307B/group65-submission/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jha58/CS3307B/group65-submission -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Screens/BlitzQuizSetupScreen.h -o moc_BlitzQuizSetupScreen.cpp

moc_CustomQuizSetupScreen.cpp: Screens/CustomQuizSetupScreen.h \
		Screens/QuizSetupScreen.h \
		User.h \
		Quiz.h \
		Question.h \
		translations/mymemorytranslator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jha58/CS3307B/group65-submission/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jha58/CS3307B/group65-submission -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Screens/CustomQuizSetupScreen.h -o moc_CustomQuizSetupScreen.cpp

moc_MainMenu.cpp: Screens/MainMenu.h \
		User.h \
		translations/mymemorytranslator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jha58/CS3307B/group65-submission/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jha58/CS3307B/group65-submission -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Screens/MainMenu.h -o moc_MainMenu.cpp

moc_ModeSelectScreen.cpp: Screens/ModeSelectScreen.h \
		User.h \
		Quiz.h \
		Question.h \
		translations/mymemorytranslator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jha58/CS3307B/group65-submission/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jha58/CS3307B/group65-submission -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Screens/ModeSelectScreen.h -o moc_ModeSelectScreen.cpp

moc_QuizScreen.cpp: Screens/QuizScreen.h \
		User.h \
		Quiz.h \
		Question.h \
		translations/mymemorytranslator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jha58/CS3307B/group65-submission/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jha58/CS3307B/group65-submission -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Screens/QuizScreen.h -o moc_QuizScreen.cpp

moc_QuizSetupScreen.cpp: Screens/QuizSetupScreen.h \
		User.h \
		Quiz.h \
		Question.h \
		translations/mymemorytranslator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jha58/CS3307B/group65-submission/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jha58/CS3307B/group65-submission -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Screens/QuizSetupScreen.h -o moc_QuizSetupScreen.cpp

moc_StatsMenu.cpp: Screens/StatsMenu.h \
		User.h \
		translations/mymemorytranslator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jha58/CS3307B/group65-submission/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jha58/CS3307B/group65-submission -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Screens/StatsMenu.h -o moc_StatsMenu.cpp

moc_mymemorytranslator.cpp: translations/mymemorytranslator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jha58/CS3307B/group65-submission/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jha58/CS3307B/group65-submission -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include translations/mymemorytranslator.h -o moc_mymemorytranslator.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp Quiz.h \
		Question.h \
		User.h \
		QuestionGeneration.h \
		ollama.hpp \
		Screens/MainMenu.h \
		translations/mymemorytranslator.h \
		Screens/StatsMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

QuestionGeneration.o: QuestionGeneration.cpp QuestionGeneration.h \
		ollama.hpp \
		Quiz.h \
		Question.h \
		User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QuestionGeneration.o QuestionGeneration.cpp

User.o: User.cpp User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o User.cpp

Quiz.o: Quiz.cpp Quiz.h \
		Question.h \
		User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Quiz.o Quiz.cpp

Question.o: Question.cpp Question.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Question.o Question.cpp

BlitzQuizScreen.o: Screens/BlitzQuizScreen.cpp Screens/BlitzQuizScreen.h \
		Screens/QuizScreen.h \
		User.h \
		Quiz.h \
		Question.h \
		translations/mymemorytranslator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BlitzQuizScreen.o Screens/BlitzQuizScreen.cpp

BlitzQuizScreen.cpp\:Zone.o: Screens/BlitzQuizScreen.cpp\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o BlitzQuizScreen.cpp:Zone.o Screens/BlitzQuizScreen.cpp:Zone.Identifier

BlitzQuizScreen.h\:Zone.o: Screens/BlitzQuizScreen.h\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o BlitzQuizScreen.h:Zone.o Screens/BlitzQuizScreen.h:Zone.Identifier

BlitzQuizSetupScreen.o: Screens/BlitzQuizSetupScreen.cpp Screens/BlitzQuizSetupScreen.h \
		Screens/QuizSetupScreen.h \
		User.h \
		Quiz.h \
		Question.h \
		translations/mymemorytranslator.h \
		Screens/BlitzQuizScreen.h \
		Screens/QuizScreen.h \
		QuestionGeneration.h \
		ollama.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BlitzQuizSetupScreen.o Screens/BlitzQuizSetupScreen.cpp

BlitzQuizSetupScreen.cpp\:Zone.o: Screens/BlitzQuizSetupScreen.cpp\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o BlitzQuizSetupScreen.cpp:Zone.o Screens/BlitzQuizSetupScreen.cpp:Zone.Identifier

BlitzQuizSetupScreen.h\:Zone.o: Screens/BlitzQuizSetupScreen.h\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o BlitzQuizSetupScreen.h:Zone.o Screens/BlitzQuizSetupScreen.h:Zone.Identifier

CustomQuizSetupScreen.o: Screens/CustomQuizSetupScreen.cpp Screens/CustomQuizSetupScreen.h \
		Screens/QuizSetupScreen.h \
		User.h \
		Quiz.h \
		Question.h \
		translations/mymemorytranslator.h \
		Screens/QuizScreen.h \
		QuestionGeneration.h \
		ollama.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CustomQuizSetupScreen.o Screens/CustomQuizSetupScreen.cpp

CustomQuizSetupScreen.cpp\:Zone.o: Screens/CustomQuizSetupScreen.cpp\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o CustomQuizSetupScreen.cpp:Zone.o Screens/CustomQuizSetupScreen.cpp:Zone.Identifier

CustomQuizSetupScreen.h\:Zone.o: Screens/CustomQuizSetupScreen.h\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o CustomQuizSetupScreen.h:Zone.o Screens/CustomQuizSetupScreen.h:Zone.Identifier

MainMenu.o: Screens/MainMenu.cpp Screens/MainMenu.h \
		User.h \
		translations/mymemorytranslator.h \
		Screens/StatsMenu.h \
		Screens/QuizScreen.h \
		Quiz.h \
		Question.h \
		Screens/ModeSelectScreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainMenu.o Screens/MainMenu.cpp

MainMenu.cpp\:Zone.o: Screens/MainMenu.cpp\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o MainMenu.cpp:Zone.o Screens/MainMenu.cpp:Zone.Identifier

MainMenu.h\:Zone.o: Screens/MainMenu.h\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o MainMenu.h:Zone.o Screens/MainMenu.h:Zone.Identifier

ModeSelectScreen.o: Screens/ModeSelectScreen.cpp Screens/ModeSelectScreen.h \
		User.h \
		Quiz.h \
		Question.h \
		translations/mymemorytranslator.h \
		Screens/MainMenu.h \
		Screens/QuizSetupScreen.h \
		Screens/BlitzQuizSetupScreen.h \
		Screens/CustomQuizSetupScreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ModeSelectScreen.o Screens/ModeSelectScreen.cpp

ModeSelectScreen.cpp\:Zone.o: Screens/ModeSelectScreen.cpp\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ModeSelectScreen.cpp:Zone.o Screens/ModeSelectScreen.cpp:Zone.Identifier

ModeSelectScreen.h\:Zone.o: Screens/ModeSelectScreen.h\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ModeSelectScreen.h:Zone.o Screens/ModeSelectScreen.h:Zone.Identifier

QuizScreen.o: Screens/QuizScreen.cpp Screens/QuizScreen.h \
		User.h \
		Quiz.h \
		Question.h \
		translations/mymemorytranslator.h \
		Screens/MainMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QuizScreen.o Screens/QuizScreen.cpp

QuizScreen.cpp\:Zone.o: Screens/QuizScreen.cpp\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o QuizScreen.cpp:Zone.o Screens/QuizScreen.cpp:Zone.Identifier

QuizScreen.h\:Zone.o: Screens/QuizScreen.h\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o QuizScreen.h:Zone.o Screens/QuizScreen.h:Zone.Identifier

QuizSetupScreen.o: Screens/QuizSetupScreen.cpp Screens/QuizSetupScreen.h \
		User.h \
		Quiz.h \
		Question.h \
		translations/mymemorytranslator.h \
		Screens/QuizScreen.h \
		Screens/ModeSelectScreen.h \
		QuestionGeneration.h \
		ollama.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QuizSetupScreen.o Screens/QuizSetupScreen.cpp

QuizSetupScreen.cpp\:Zone.o: Screens/QuizSetupScreen.cpp\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o QuizSetupScreen.cpp:Zone.o Screens/QuizSetupScreen.cpp:Zone.Identifier

QuizSetupScreen.h\:Zone.o: Screens/QuizSetupScreen.h\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o QuizSetupScreen.h:Zone.o Screens/QuizSetupScreen.h:Zone.Identifier

StatsMenu.o: Screens/StatsMenu.cpp Screens/StatsMenu.h \
		User.h \
		translations/mymemorytranslator.h \
		Screens/MainMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StatsMenu.o Screens/StatsMenu.cpp

StatsMenu.cpp\:Zone.o: Screens/StatsMenu.cpp\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o StatsMenu.cpp:Zone.o Screens/StatsMenu.cpp:Zone.Identifier

StatsMenu.h\:Zone.o: Screens/StatsMenu.h\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o StatsMenu.h:Zone.o Screens/StatsMenu.h:Zone.Identifier

mymemorytranslator.o: translations/mymemorytranslator.cpp translations/mymemorytranslator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mymemorytranslator.o translations/mymemorytranslator.cpp

mymemorytranslator.cpp\:Zone.o: translations/mymemorytranslator.cpp\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o mymemorytranslator.cpp:Zone.o translations/mymemorytranslator.cpp:Zone.Identifier

mymemorytranslator.h\:Zone.o: translations/mymemorytranslator.h\:Zone.Identifier 
	$(CC) -c $(CFLAGS) $(INCPATH) -o mymemorytranslator.h:Zone.o translations/mymemorytranslator.h:Zone.Identifier

moc_BlitzQuizScreen.o: moc_BlitzQuizScreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BlitzQuizScreen.o moc_BlitzQuizScreen.cpp

moc_BlitzQuizSetupScreen.o: moc_BlitzQuizSetupScreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BlitzQuizSetupScreen.o moc_BlitzQuizSetupScreen.cpp

moc_CustomQuizSetupScreen.o: moc_CustomQuizSetupScreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CustomQuizSetupScreen.o moc_CustomQuizSetupScreen.cpp

moc_MainMenu.o: moc_MainMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainMenu.o moc_MainMenu.cpp

moc_ModeSelectScreen.o: moc_ModeSelectScreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ModeSelectScreen.o moc_ModeSelectScreen.cpp

moc_QuizScreen.o: moc_QuizScreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QuizScreen.o moc_QuizScreen.cpp

moc_QuizSetupScreen.o: moc_QuizSetupScreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QuizSetupScreen.o moc_QuizSetupScreen.cpp

moc_StatsMenu.o: moc_StatsMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StatsMenu.o moc_StatsMenu.cpp

moc_mymemorytranslator.o: moc_mymemorytranslator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mymemorytranslator.o moc_mymemorytranslator.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

